Add commas
Minervis-GmbH/BigBlueButton-Ilias-Plugin pull request #13
Opened 2021-04-06 21:36 UTC by jeph864

2021-05-11 08:22 UTC, Rillke requested changes
Please close this PR.

2021-05-11 08:22 UTC, Rillke commented on plugin.php
> -$version = "1.0.14";
The commit message and pull request title does not match what's done in the code.

You are actually increasing the version number.

2021-05-11 08:22 UTC, Rillke commented on plugin.php
> -$version = "1.0.14";
And actually, it's already merged, so this PR can be closed.

2021-05-12 05:04 UTC, jeph864 commented
@Rillke 
thanks for the info!

2021-05-12 05:04 UTC, closed without merging